### ISSUE TITLE
bundles blocked~ 

### ISSUE THREAD

**Issue by helloCheng09** [mendix/widgets-tools#72] opened 2023-12-12 12:45 UTC
Please log your issues via http://support.mendix.com for the best assistance.

When you like to discuss complex technical issues, improvements, pull requests, questions, or suggestions feel free to
contact us directly via this GitHub issue.

**Reporting Bugs** When reporting bugs, please follow these guidelines to ensure quick responses:
{
  "name": "aplusswipera",
  "widgetName": "APlusSwiperA",
  "version": "1.0",
  "description": "My widget description",
  "copyright": "VWA 2023",
  "author": "Cheng Shaobo",
  "engines": {
    "node": ">=16"
  },
  "license": "Apache-2.0",
  "config": {
    "projectPath": "../my-widget-test",
    "mendixHost": "http://localhost:8080",
    "developmentPort": 3000
  },
  "packagePath": "vwa",
  "scripts": {
    "start": "pluggable-widgets-tools start:server",
    "dev": "pluggable-widgets-tools start:web",
    "build": "pluggable-widgets-tools build:web",
    "lint": "pluggable-widgets-tools lint",
    "lint:fix": "pluggable-widgets-tools lint:fix",
    "prerelease": "npm run lint",
    "release": "pluggable-widgets-tools release:web"
  },
  "devDependencies": {
    "@mendix/pluggable-widgets-tools":  "^10.0.0"
  },
  "dependencies": {
    "classnames": "^2.2.6"
  },
  "resolutions": {
    "react": "18.2.0",
    "react-native": "0.70.7"
  },
  "overrides": {
    "react": "18.2.0",
    "react-native": "0.70.7"
  }
}

**Describe the bug** Write a clear and concise description of what the bug is.
![image](https://github.com/mendix/widgets-tools/assets/41097785/a69ed00d-47c0-42c2-9189-ee34c5659152)

**To Reproduce** Give a few steps to reproduce the behavior. For example:
why 【npm run start】can not rollup the bundles ~~???

**Comment by jeffersonRibeiro** [comment] 2024-02-19 09:04
Hi, could you please give more details?

I don't see what the problem is.

In your screenshot, it just shows the project bundling and sometimes the bundling process can take a while to execute.

You may also try the latest release https://www.npmjs.com/package/@mendix/pluggable-widgets-tools/v/10.7.1 which fixes the Rollup bundling issue with module-level directives.

**Comment by jeffersonRibeiro** [comment] 2024-03-12 09:24
I will close the issue report thread. 

If the issue occurs again feel free to open another thread and we will be glad to assist.

**Closed by jeffersonRibeiro** 2024-03-12 09:24 UTC
